hello/urls.py
from django.urls import path

from . import views

urlpatterns =[
    path("", views.index, name="index"),
    path("brain", views.brain, name="brain"),
    path("david", views.david, name="david"),
    path("<str:name>", views.greet, name="greet")
]

myapp/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'wiki' #added app name

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.entry, name="entry")
]

wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def brain(request):
    return HttpResponse("hello brain")

def david(request):
    return HttpResponse("Hello, David!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name":name.capitalize()
    })

newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.date
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

tasks/views.py
from django import forms
from django.shortcuts import render


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")


# Create your views here.
tasks = ["foo", "bar", "baz"]
def index(request):
    return render(request,"tasks/index.html",{
        "tasks":tasks
    })

def add(request):
    return render(request, "tasks/add.html",{
        "form":NewTaskForm
    })

wiki/wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . import util

from markdown2 import Markdown

markdowner = Markdown()


def index(request):
    entries = util.list_entries()
    return render(request, "encyclopedia/index.html", {
        "entries": entries
    })

def entry(request, title):
    page = util.get_entry(title)
    
    if page is None:
        return HttpResponse("Page Not Found")
    body = markdowner.convert(page)
    return render(request, "encyclopedia/topic.html", {
        "title": title,
        "titleBody": body
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, World</h1>
</body>
</html>

newyear/templates/newyear/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>isItNewyear</title>
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}
{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="submit">
        <a href="{% url 'tasks:index' %}">View tasks</a>

    </form>
{% endblock%}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}
{% block body %}
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
        
    </ul>
    <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/{{ entry }}">{{ entry }}</a></li> <!-- added the redirected -->>
        {% endfor %}
    </ul>

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form>
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    Create New Page
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/wiki/encyclopedia/templates/encyclopedia/topic.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<p>{{ titleBody|safe }}</p>

{% endblock %}